$schema: 'http://json-schema.org/schema#'
$async: true
title: PluginDefinition
type: object
description: >
  Represents a CIRCUS CS plug-in (app).
properties:
  pluginId:
    type: string
    format: dockerId
    description: >
      :key: The unique ID of this plug-in.
  pluginName:
    type: string
    minLength: 1
    maxLength: 128
    description: >
      Displayed plug-in name.
  version:
    type: string
    format: semver
    description: >
      Semver-compatible plug-in version.
  type:
    enum: ['CAD']
    description: >
      Plug-in type. Currently the only supported value is 'CAD'.
  description:
    type: string
    maxLength: 128
    description: >
      Short text that describes what this plug-in does.
  runConfiguration:
    type: object
    description: >
      Installation-specific configurations.
    properties:
      timeout:
        type: integer
        minValue: 0
        description: >
          Execution timeout in seconds. Specify 0 if there is no timeout.
      gpus:
        type: string
        description: >
          Passed to Docker container.
    additionalProperties: false
  icon:
    $ref: icon
  displayStrategy:
    type: array
    items:
      type: object
      properties:
        type:
          type: string
        feedbackKey:
          type: string
        caption:
          type: string
        options:
          type: object
    description: >
      Determines how plug-in results are displayed and how feedback is collected.
additionalProperties: false
