$schema: 'http://json-schema.org/schema#'
$async: true
title: Project
type: object
properties:
  projectId:
    type: string
    maxLength: 64
    description: >
      :key: Randomly-generated project ID. It must be globally unique.
  projectName:
    type: string
    maxLength: 64
    description: >
      Short name for this project.
  description:
    type: string
    maxLength: 1024
    description: >
      Optinal arbitrary text to explain this project.
  tags:
    type: array
    items: { type: 'object' }
    description: >
      List of tags available in this project.
  caseAttributesSchema:
    type: array
    items: { $ref: 'schemaEntry' }
    description: >
      The schema of case attributes.
  labelAttributesSchema:
    type: array
    items: { $ref: 'schemaEntry' }
    description:
      The schema of label attributes.
  windowPresets:
    type: array
    items:
      type: object
      properties:
        label: { type: 'string' }
        level: { type: 'number' }
        width: { type: 'number' }
      required: ['label', 'level', 'width']
  windowPriority:
    type: string
    enum: ['dicom,auto', 'auto']
  groups:
    type: array
    items: { type: number }
