name: Jest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
      fail-fast: false

    services:
      mongodb:
        image: mongo:4.2.2-bionic
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: |
          npm install
      - name: Prepare docker images
        run: |
          docker pull hello-world
          docker pull circuscad/dicom_voxel_dump:1.0.0
          docker tag circuscad/dicom_voxel_dump:1.0.0 circus/dicom_voxel_dump:1.0
          cd test/docker
          node build.js
      - name: npm test
        run: npm test
        env:
          CI: true
