extends:
  - eslint:recommended
parserOptions:
  ecmaVersion: 2018
  sourceType: module
env:
  es6: true
  node: true
  mocha: true
rules:
  indent: [2, 2, { SwitchCase: 1 }]
  quotes: [2, 'single', { avoidEscape: true }]
  padding-line-between-statements:
    - 'error'
    - { blankLine: 'always', prev: 'function', next: 'function' }
    - { blankLine: 'always', prev: 'import', next: '*' }
    - { blankLine: 'any', prev: 'import', next: 'import' }
  no-unused-vars: [0]
  no-useless-escape: [0]
  no-constant-condition: [2, { checkLoops: false }]
  semi: [2, 'always']
  no-var: 'error'
  prefer-const: 'error'
  no-console: [0]
  no-empty-pattern: [0]
